//////////////////////////////////////////////////////////////////////////////
//					Ray Tracing in One Weekend
//				Shadertoy port by João V. B. Silva
//
// 	This is my first time doing anything remotely related to shaders, so you
// might see a lot of hacks and non-recommended things here. Tried to stay as
// close to Peter Shirley's book as I could. Feedback is appreciated :)
//
//  The scene (i.e. geometries & BRDFs) is generated by a Python script. You 
// can find it (as well as a copy of these files) on this repository:
// https://github.com/joaovbs96/shadertoy_raytracer
//
//////////////////////////////////////////////////////////////////////////////

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
  // Accumulate and output to screen
  vec2 uv = fragCoord.xy / iResolution.xy;
  vec4 oldColor = texture(iChannel0, uv);

  fragColor = vec4(sqrt(oldColor.rgb / float(iFrame)), 1.0f);
}